server:
  hostname: "shiny.dide.ic.ac.uk"
  email: "r.fitzjohn@imperial.ac.uk"
  port_http: 80
  port_https: 443
  port_admin: 9000
  # used for the self-signed certificate
  country: UK
  state: London
  organisation: DIDE

vault:
  address: "https://vault.dide.ic.ac.uk:8200"
  root: "/secret/shiny.dide"

apps:
  typochallenge:
    type: github
    spec: mrc-ide/typochallenge
    protect:
      paths:
        - emails.db
        - contributions
    secret:
      .redis:
        path: "misc/redis-url"
        field: value
      .googlesheets-oauth:
        path: "misc/googlesheets-oauth"
        field: token
        binary: true
    schedule:
      update_googlesheets:
        frequency: "@hourly"
        command: ./update_googlesheets
    admin:
      - acori

  eppasmviewer:
    type: github
    spec: mrc-ide/eppasmviewer/inst/shiny/eppasmviewer
    auth:
      type: deploy_key
    groups:
      - admin
      - epidem
    admin:
      - jeff

  polici:
    type: github
    spec: arranhamlet/POLICI

  seasonal_hrp2:
    type: github
    spec: ojwatson/hrp2malaRia/inst/shiny-seasonality/app
    admin: ojwatson

  flupractical2:
    type: github
    spec: ada-w-yan/fitr
    auth:
      type: deploy_key
    admin:
      - ayan

  chainchecker:
    type: github
    spec: imperialebola2018/chainchecker 
    auth:
      type: deploy_key
    admin:
      - kgaythorpe
      
RAPTOR:
    type: github
    spec: mrc-ide/RAPTOR 
    auth:
      type: deploy_key
    admin:
      - kgaythorpe
      - arranhamlet
      
  kpcascade:
    type: github
    spec: osymandius/kpcascade
    admin:
      - ostevens
  
  # Group of related applications for MSc teaching November 2018
  stochasticity-practical/example1:
    type: github
    spec: mrc-ide/stochasticity-practical/example1
  stochasticity-practical/example2:
    type: github
    spec: mrc-ide/stochasticity-practical/example2
  stochasticity-practical/example3:
    type: github
    spec: mrc-ide/stochasticity-practical/example3
  stochasticity-practical/example4:
    type: github
    spec: mrc-ide/stochasticity-practical/example4
  stochasticity-practical/example5:
    type: github
    spec: mrc-ide/stochasticity-practical/example5

  hello:
    type: local
    spec: hello

  test:
    type: local
    spec: test
    groups:
      - dide-internal

  shiny90:
    type: github
    spec: mrc-ide/shiny90
    admin:
      - alex

  malaria_vector_control_decisions_tool:
    type: github
    spec: mrc-ide/shiny-malaria-UI
    admin: ellie
    auth:
      type: deploy_key
    groups:
      - MVC
    
groups:
  dide-internal:
    - rich
    - jeff
    - acori
  epidem:
    - epidem
    - jeff
  admin:
    - rich
  MVC:    
    - ellie
    - guestTester

